OpTableFor0NNN		FDB	Loop				; nop - 00
			FDB	Loop				; nop - 01
			FDB	Loop				; nop - 02
			FDB	Loop				; nop - 03
			FDB	Loop				; nop - 04
			FDB	Loop				; nop - 05
			FDB	Loop				; nop - 06
			FDB	Loop				; nop - 07
			FDB	Loop				; nop - 08
			FDB	Loop				; nop - 09
			FDB	Loop				; nop - 0a
			FDB	Loop				; nop - 0b
			FDB	Loop				; nop - 0c
			FDB	Loop				; nop - 0d
			FDB	Loop				; nop - 0e
			FDB	Loop				; nop - 0f
			FDB	Loop				; nop - 10
			FDB	Loop				; nop - 11
			FDB	Loop				; nop - 12
			FDB	Loop				; nop - 13
			FDB	Loop				; nop - 14
			FDB	Loop				; nop - 15
			FDB	Loop				; nop - 16
			FDB	Loop				; nop - 17
			FDB	Loop				; nop - 18
			FDB	Loop				; nop - 19
			FDB	Loop				; nop - 1a
			FDB	Loop				; nop - 1b
			FDB	Loop				; nop - 1c
			FDB	Loop				; nop - 1d
			FDB	Loop				; nop - 1e
			FDB	Loop				; nop - 1f
			FDB	Loop				; nop - 20
			FDB	Loop				; nop - 21
			FDB	Loop				; nop - 22
			FDB	Loop				; nop - 23
			FDB	Loop				; nop - 24
			FDB	Loop				; nop - 25
			FDB	Loop				; nop - 26
			FDB	Loop				; nop - 27
			FDB	Loop				; nop - 28
			FDB	Loop				; nop - 29
			FDB	Loop				; nop - 2a
			FDB	Loop				; nop - 2b
			FDB	Loop				; nop - 2c
			FDB	Loop				; nop - 2d
			FDB	Loop				; nop - 2e
			FDB	Loop				; nop - 2f
			FDB	Loop				; nop - 30
			FDB	Loop				; nop - 31
			FDB	Loop				; nop - 32
			FDB	Loop				; nop - 33
			FDB	Loop				; nop - 34
			FDB	Loop				; nop - 35
			FDB	Loop				; nop - 36
			FDB	Loop				; nop - 37
			FDB	Loop				; nop - 38
			FDB	Loop				; nop - 39
			FDB	Loop				; nop - 3a
			FDB	Loop				; nop - 3b
			FDB	Loop				; nop - 3c
			FDB	Loop				; nop - 3d
			FDB	Loop				; nop - 3e
			FDB	Loop				; nop - 3f
			FDB	Loop				; nop - 40
			FDB	Loop				; nop - 41
			FDB	Loop				; nop - 42
			FDB	Loop				; nop - 43
			FDB	Loop				; nop - 44
			FDB	Loop				; nop - 45
			FDB	Loop				; nop - 46
			FDB	Loop				; nop - 47
			FDB	Loop				; nop - 48
			FDB	Loop				; nop - 49
			FDB	Loop				; nop - 4a
			FDB	Loop				; nop - 4b
			FDB	Loop				; nop - 4c
			FDB	Loop				; nop - 4d
			FDB	Loop				; nop - 4e
			FDB	Loop				; nop - 4f
			FDB	Loop				; nop - 50
			FDB	Loop				; nop - 51
			FDB	Loop				; nop - 52
			FDB	Loop				; nop - 53
			FDB	Loop				; nop - 54
			FDB	Loop				; nop - 55
			FDB	Loop				; nop - 56
			FDB	Loop				; nop - 57
			FDB	Loop				; nop - 58
			FDB	Loop				; nop - 59
			FDB	Loop				; nop - 5a
			FDB	Loop				; nop - 5b
			FDB	Loop				; nop - 5c
			FDB	Loop				; nop - 5d
			FDB	Loop				; nop - 5e
			FDB	Loop				; nop - 5f
			FDB	Loop				; nop - 60
			FDB	Loop				; nop - 61
			FDB	Loop				; nop - 62
			FDB	Loop				; nop - 63
			FDB	Loop				; nop - 64
			FDB	Loop				; nop - 65
			FDB	Loop				; nop - 66
			FDB	Loop				; nop - 67
			FDB	Loop				; nop - 68
			FDB	Loop				; nop - 69
			FDB	Loop				; nop - 6a
			FDB	Loop				; nop - 6b
			FDB	Loop				; nop - 6c
			FDB	Loop				; nop - 6d
			FDB	Loop				; nop - 6e
			FDB	Loop				; nop - 6f
			FDB	Loop				; nop - 70
			FDB	Loop				; nop - 71
			FDB	Loop				; nop - 72
			FDB	Loop				; nop - 73
			FDB	Loop				; nop - 74
			FDB	Loop				; nop - 75
			FDB	Loop				; nop - 76
			FDB	Loop				; nop - 77
			FDB	Loop				; nop - 78
			FDB	Loop				; nop - 79
			FDB	Loop				; nop - 7a
			FDB	Loop				; nop - 7b
			FDB	Loop				; nop - 7c
			FDB	Loop				; nop - 7d
			FDB	Loop				; nop - 7e
			FDB	Loop				; nop - 7f
			FDB	Loop				; nop - 80
			FDB	Loop				; nop - 81
			FDB	Loop				; nop - 82
			FDB	Loop				; nop - 83
			FDB	Loop				; nop - 84
			FDB	Loop				; nop - 85
			FDB	Loop				; nop - 86
			FDB	Loop				; nop - 87
			FDB	Loop				; nop - 88
			FDB	Loop				; nop - 89
			FDB	Loop				; nop - 8a
			FDB	Loop				; nop - 8b
			FDB	Loop				; nop - 8c
			FDB	Loop				; nop - 8d
			FDB	Loop				; nop - 8e
			FDB	Loop				; nop - 8f
			FDB	Loop				; nop - 90
			FDB	Loop				; nop - 91
			FDB	Loop				; nop - 92
			FDB	Loop				; nop - 93
			FDB	Loop				; nop - 94
			FDB	Loop				; nop - 95
			FDB	Loop				; nop - 96
			FDB	Loop				; nop - 97
			FDB	Loop				; nop - 98
			FDB	Loop				; nop - 99
			FDB	Loop				; nop - 9a
			FDB	Loop				; nop - 9b
			FDB	Loop				; nop - 9c
			FDB	Loop				; nop - 9d
			FDB	Loop				; nop - 9e
			FDB	Loop				; nop - 9f
			FDB	Loop				; nop - a0
			FDB	Loop				; nop - a1
			FDB	Loop				; nop - a2
			FDB	Loop				; nop - a3
			FDB	Loop				; nop - a4
			FDB	Loop				; nop - a5
			FDB	Loop				; nop - a6
			FDB	Loop				; nop - a7
			FDB	Loop				; nop - a8
			FDB	Loop				; nop - a9
			FDB	Loop				; nop - aa
			FDB	Loop				; nop - ab
			FDB	Loop				; nop - ac
			FDB	Loop				; nop - ad
			FDB	Loop				; nop - ae
			FDB	Loop				; nop - af
			FDB	Loop				; nop - b0
			FDB	Loop				; nop - b1
			FDB	Loop				; nop - b2
			FDB	Loop				; nop - b3
			FDB	Loop				; nop - b4
			FDB	Loop				; nop - b5
			FDB	Loop				; nop - b6
			FDB	Loop				; nop - b7
			FDB	Loop				; nop - b8
			FDB	Loop				; nop - b9
			FDB	Loop				; nop - ba
			FDB	Loop				; nop - bb
			FDB	Loop				; nop - bc
			FDB	Loop				; nop - bd
			FDB	Loop				; nop - be
			FDB	Loop				; nop - bf
			FDB	Loop				; nop - c0
			FDB	Loop				; nop - c1
			FDB	Loop				; nop - c2
			FDB	Loop				; nop - c3
			FDB	Loop				; nop - c4
			FDB	Loop				; nop - c5
			FDB	Loop				; nop - c6
			FDB	Loop				; nop - c7
			FDB	Loop				; nop - c8
			FDB	Loop				; nop - c9
			FDB	Loop				; nop - ca
			FDB	Loop				; nop - cb
			FDB	Loop				; nop - cc
			FDB	Loop				; nop - cd
			FDB	Loop				; nop - ce
			FDB	Loop				; nop - cf
			FDB	Loop				; nop - d0
			FDB	Loop				; nop - d1
			FDB	Loop				; nop - d2
			FDB	Loop				; nop - d3
			FDB	Loop				; nop - d4
			FDB	Loop				; nop - d5
			FDB	Loop				; nop - d6
			FDB	Loop				; nop - d7
			FDB	Loop				; nop - d8
			FDB	Loop				; nop - d9
			FDB	Loop				; nop - da
			FDB	Loop				; nop - db
			FDB	Loop				; nop - dc
			FDB	Loop				; nop - dd
			FDB	Loop				; nop - de
			FDB	Loop				; nop - df
			FDB	Op00E0_ClearScreen		; EO - ClearScreen
			FDB	Loop				; nop - e1
			FDB	Loop				; nop - e2
			FDB	Loop				; nop - e3
			FDB	Loop				; nop - e4
			FDB	Loop				; nop - e5
			FDB	Loop				; nop - e6
			FDB	Loop				; nop - e7
			FDB	Loop				; nop - e8
			FDB	Loop				; nop - e9
			FDB	Loop				; nop - ea
			FDB	Loop				; nop - eb
			FDB	Loop				; nop - ec
			FDB	Loop				; nop - ed
			FDB	Loop				; nop - ee
			FDB	Loop				; nop - ef
			FDB	Loop				; nop - f0
			FDB	Loop				; nop - f1
			FDB	Loop				; nop - f2
			FDB	Loop				; nop - f3
			FDB	Loop				; nop - f4
			FDB	Loop				; nop - f5
			FDB	Loop				; nop - f6
			FDB	Loop				; nop - f7
			FDB	Loop				; nop - f8
			FDB	Loop				; nop - f9
			FDB	Loop				; nop - fa
			FDB	Loop				; nop - fb
			FDB	Loop				; nop - fc
			FDB	Loop				; nop - fd
			FDB	Loop				; nop - fe
			FDB	Loop				; nop - ff 			
